---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: document
  path: src/index.md
  label: Work

- type: document
  path: src/about.md
  label: About

- type: document
  path: src/uses.md
  label: Uses

- type: document
  path: src/privacy-policy.md
  label: Privacy Policy

- type: document
  path: src/terms-and-conditions.md
  label: Terms and Conditions

- type: document
  path: src/the-website.md
  label: The Website

- type: document
  path: src/404.md
  label: 404

- type: document
  path: src/_data/projects.js
  label: Projects

upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
